# Generated by Django 3.2.6 on 2021-08-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechNews',
            new_name='Tech',
        ),
    ]
