# Generated by Django 3.2.6 on 2021-08-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='interests',
            field=models.ManyToManyField(related_name='interests', to='app.UserProfile'),
        ),
    ]
