# Generated by Django 3.2.6 on 2021-08-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_group_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterField(
            model_name='stories',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
