# Generated by Django 3.2.6 on 2021-08-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_fundraiser_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='event_date',
        ),
    ]
