# Generated by Django 3.2.6 on 2021-08-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_fundraiser_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='event_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
