# Generated by Django 3.2.6 on 2021-08-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210803_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
