# Generated by Django 3.2.6 on 2021-08-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='image2_path',
            field=models.ImageField(blank=True, null=True, upload_to='Ideas/'),
        ),
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
