# Generated by Django 3.2.6 on 2021-08-03 13:10

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField()),
                ('image_path', models.ImageField(upload_to='Stories/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
    ]
